model_config:
  model_name: "PINNsformer"
  net_prefixes: ["net"]
  loss_terms: ["pres", "velx", "vely", "bc", "ic"]
  d_out: 3
  d_hidden: 32
  d_model: 32
  N: 1
  heads: 2
  ores_weight: 1
  velx_weight: 1
  vely_weight: 1
  bc_weight: 1
  ic_weight: 1
train_config:
  train_steps: 100000
  learning_rate: 0.001
  decay_every: 2000
  update_every: 1000
  print_every: 100
  alpha: 0.9
  batch_size: 1024